### ISSUE TITLE
Station P1 edge 6.4-rc4 drops to initramfs

### ISSUE THREAD

**Issue by EvilOlaf** [150balbes/build#46]
Hey man,

I built an image for the Station P1 from your latest commit to `armbian-tv` (https://github.com/150balbes/build/commit/e4e40eabfae3f179b6e5f1baf1cc03af4f64d752) with `edge` as BRANCH. Building went good so far.
However when trying to boot it from microSD it drops to initramfs. 

Known issue? Or am I missing something?

I will give `current` a shot later as well. 

Cheers

Edit: `current` boots.

**Comment by 150balbes** [comment]
Sorry, I just saw the question (for some reason I do not receive notifications about the creation and questions). Is the question still relevant ?

**Comment by EvilOlaf** [comment]
Did not give it a try since then. I will retry once I get a chance.
