### ISSUE TITLE
Unable to compile 6.6.y kernel

### ISSUE THREAD

**Issue by newdev8** [150balbes/build#47]
Hello, thanks for maintaining the Orange Pi 5 board, I've had no issues compiling the kernel up to 6.5.9, but when trying to compile the 6.6.y kernel I get an error.

I will update my answer when I try to recompile it again to give you the exact output.

EDIT: I was able to compile the 6.6.1 kernel using the original [armbian/build](https://github.com/armbian/build) repo, but the resulting image does not contain `vmlinuz`, `initrd.img` nor `dtbs`.

EDIT2: It looks like those files were in another partition of the image. I was able to successfully update to kernel 6.6.1.

**Comment by xierongchuan** [comment]
> Hello, thanks for maintaining the Orange Pi 5 board, I've had no issues compiling the kernel up to 6.5.9, but when trying to compile the 6.6.y kernel I get an error.
> 
> I will update my answer when I try to recompile it again to give you the exact output.
> 
> EDIT: I was able to compile the 6.6.1 kernel using the original [armbian/build](https://github.com/armbian/build) repo, but the resulting image does not contain `vmlinuz`, `initrd.img` nor `dtbs`.
> 
> EDIT2: It looks like those files were in another partition of the image. I was able to successfully update to kernel 6.6.1.

I can't seem to find a build for the MangoPi MQ-Pro anymore, as the one on the official website is no longer available.

Also, can I use the official armbian/build repository to build an image for the MangoPi MQ-Pro?
