### ISSUE TITLE
PACKAGE_LIST_RM remove partial names

### ISSUE THREAD

**Issue by andrianovs** [150balbes/build#51]
Hello.

I try to change package list in image and found some bug.

When I set
PACKAGE_LIST_RM="bluetooth" in userpatches/lib.config
some package names in PACKAGE_LIST corrupts.

Original PACKAGE_LIST
`... system-config-printer-common bluetooth bluez ... pulseaudio-module-gconf pulseaudio-module-bluetooth gnome-orca ...`

PACKAGE_LIST after applying PACKAGE_LIST_RM
`... system-config-printer-common bluez ... pulseaudio-module-gconf pulseaudio-module- gnome-orca ...`

Package with name 'bluetooth' removed as expected, but name of package 'pulseaudio-module-bluetooth' was truncated to 'pulseaudio-module-'.
I think name of 'pulseaudio-module-bluetooth' must not change.

```
# sed --version
sed (GNU sed) 4.2.2
```

May be fix like that:
```
#!/bin/bash

PACKAGE_LIST="first some-package another-package bluetooth another-bluetooth last"
PACKAGE_LIST_RM="bluetooth first last"

echo 'Before:'
echo $PACKAGE_LIST

echo 'Remove:'
echo $PACKAGE_LIST_RM

echo 'Bug:'
echo $(sed -r "s/\b($(tr ' ' '|' <<< $PACKAGE_LIST_RM))\b//g" <<< $PACKAGE_LIST)

echo 'Fixed:'
echo $(sed -r "s/\s($(tr ' ' '|' <<< $PACKAGE_LIST_RM))\s/ /g" <<< " $PACKAGE_LIST ")
```
It add spaces an start and end of PACKAGE_LIST to correct remove first and last package, and replaces only full matches package.
Original regexp use \b and not work correctly with '-'.

```
Before:
first some-package another-package bluetooth another-bluetooth last
Remove:
bluetooth first last
Bug:
some-package another-package another-
Fixed:
some-package another-package another-bluetooth
```

**Comment by 150balbes** [comment]
Hi
I don't use lists with exceptions. If you have this working, I can add your fix.

**Comment by andrianovs** [comment]
Yes, last version with SED_TASK works, as far as I could verify.
I try remove various packages with this patch and check result list.

**Comment by 150balbes** [comment]
IMHO 
If you are planning on building your own version of the image, I recommend not using delete mode. Deleting can occur strange situation. When coupled to an excluded package, the dependency will be removed in the desired package. It is better to edit the set of files in the config file or add your new list (variable). I've lost a lot of time searching for such mistakes many times. When in the composition of the way of suddenly something changed without my editing. After clarification was provided that the maintainer in a network repository, change the dependencies of a package, which I was used.

**Comment by andrianovs** [comment]
It is better to replace in lib.config all lists, which used after this file import.
I see these variables
```
PACKAGE_LIST
PACKAGE_LIST_RELEASE
PACKAGE_LIST_ADDITIONAL
PACKAGE_LIST_DESKTOP
```
and don't set PACKAGE_LIST_RM?

In this case my fix don't needed.

**Comment by 150balbes** [comment]
Yes, it is better to change these variables immediately in the file "/lib/configuration.sh"

PACKAGE_LIST
PACKAGE_LIST_RELEASE
PACKAGE_LIST_ADDITIONAL
PACKAGE_LIST_DESKTOP

**Comment by andrianovs** [comment]
Thanks,
I do it.
