### ISSUE TITLE
Select DE enviroument from config-custom.conf

### ISSUE THREAD

**Issue by andrianovs** [150balbes/build#52]
Hello.

Script lib / main.sh can not skip the selection of the desktop environment,
You can set the BUILD_DESKTOP variable in config-custom.conf, and the menu is not displayed.
But the variable BUILD_DESKTOP_DE does not check the file lib / main.sh and the menu is displayed in any case.

```
 # options DE
-if [[ $KERNEL_ONLY != yes && $BUILD_DESKTOP = yes && -z $BUILD_DESKTOP_DE ]]; then
+if [[ $KERNEL_ONLY != yes && $BUILD_DESKTOP = yes ]]; then
```

**Comment by andrianovs** [comment]
Sorry, in my example, the original and resulting files are confused.
Original is
```
if [[ $KERNEL_ONLY != yes && $BUILD_DESKTOP = yes ]]; then
```
patched -
```
if [[ $KERNEL_ONLY != yes && $BUILD_DESKTOP = yes && -z $BUILD_DESKTOP_DE ]]; then
```

And when custom-config.conf like this
```
BUILD_DESKTOP=yes
BUILD_DESKTOP_DE=xfce
```
menu for DE selection don't show.

**Comment by 150balbes** [comment]
Ok

**Comment by andrianovs** [comment]
Hello.
Patch was lost in commit 2f92a32.
It's mistake or not?

**Comment by 150balbes** [comment]
Hi
No, it's not a mistake. This patch breaks down the graphical build shell. Need more debugging and modifying the patch that he would not break the work of the graphic shell.

**Comment by andrianovs** [comment]
How to run compilation to reproduce break?
I try to fix it.

**Comment by 150balbes** [comment]
Run script "./compile.sh" and select the graphical menu build FulOS\do not change\Amlogic-s905x\default\bionic\image desktop\Mate

**Comment by andrianovs** [comment]
Selection of DE not working because variable BUILD_DESKTOP_DE set to "server" before show menu for selection server or desktop variant, and in next check it's not empty.
I don't know how value "server" used later and offer set it after select value "no" of  BUILD_DESKTOP.

```
diff --git a/lib/main.sh b/lib/main.sh
index c767ba9..6c928fe 100644
--- a/lib/main.sh
+++ b/lib/main.sh
@@ -218,7 +218,6 @@ if [[ $KERNEL_ONLY != yes && -z $RELEASE ]]; then
 fi

 if [[ $KERNEL_ONLY != yes && -z $BUILD_DESKTOP ]]; then
-       BUILD_DESKTOP_DE="server"
        options=()
        options+=("no" "Image with console interface (server)")
        options+=("yes" "Image with desktop environment")
@@ -226,10 +225,11 @@ if [[ $KERNEL_ONLY != yes && -z $BUILD_DESKTOP ]]; then
                $TTY_Y $TTY_X $(($TTY_Y - 8)) "${options[@]}")
        unset options
        [[ -z $BUILD_DESKTOP ]] && exit_with_error "No option selected"
+       [[ $BUILD_DESKTOP != yes ]] && BUILD_DESKTOP_DE="server"
 fi

 # options DE
-if [[ $KERNEL_ONLY != yes && $BUILD_DESKTOP = yes ]]; then
+if [[ $KERNEL_ONLY != yes && $BUILD_DESKTOP = yes && -z $BUILD_DESKTOP_DE ]]; then
        options=()
        options+=("xfce" "Image with desktop XFCE")
        options+=("mate" "Image with desktop MATE")
```

**Comment by 150balbes** [comment]
I'll check on that tomorrow.

**Comment by 150balbes** [comment]
fix
