### ISSUE TITLE
Problems with build script

### ISSUE THREAD

**Issue by DiApostola** [150balbes/build#53]
Running into this on a build server that otherwise works find for regular Armbian. Pull from the 150balbes/build GitHub just as with the Armbian, run the ./compile.sh, pick straight Ubuntu 16. It goes through the config process but then errors out with the following:

  INSTALL debian/headertmp/usr/include/asm/ (36 files)
dpkg-deb: building package 'linux-headers-4.18.0-rc4-aml-s905' in '../linux-headers-4.18.0-rc4-aml-s905_5.44_arm64.deb'.
dpkg-deb: building package 'linux-libc-dev' in '../linux-libc-dev_5.44_arm64.deb'.
dpkg-deb: building package 'linux-image-4.18.0-rc4-aml-s905' in '../linux-image-4.18.0-rc4-aml-s905_5.44_arm64.deb'.
dpkg-deb: building package 'linux-image-4.18.0-rc4-aml-s905-dbg' in '../linux-image-4.18.0-rc4-aml-s905-dbg_5.44_arm64.deb'.
 dpkg-genchanges -b >../linux-4.18.0-rc4-aml-s905_5.44_arm64.changes
dpkg-genchanges: binary-only upload (no source code included)
 dpkg-source --after-build master
dpkg-buildpackage: binary-only upload (no source included)
dpkg-deb: building package 'linux-source-4.18.0-rc4-next-aml-s905' in '/home/ubdude/s905/build/.tmp/linux-source-next-aml-s905_5.44_all.deb'.
dpkg-deb: error: failed to read archive '/home/ubdude/s905/build/output/debs/linux-image-next-aml-s905_5.44_arm64.deb': No such file or directory
[ o.k. ] Creating board support package [ aml-s905 next ]
[ .... ] Fingerprinting
[ o.k. ] Building package [ linux-xenial-root-next-aml-s905 ]
[ o.k. ] Starting rootfs and image building process for [ aml-s905 xenial ]
[ o.k. ] Creating new rootfs for [ xenial ]
[ o.k. ] Installing base system [ Stage 1/2 ]
I: Retrieving InRelease
I: Retrieving Release
E: Failed getting release file http://localhost:3142/ports.ubuntu.com/dists/xenial/Release
[ error ] ERROR in function create_rootfs_cache [ debootstrap-ng.sh:127 ]
[ error ] Debootstrap base system first stage failed
[ o.k. ] Process terminated
[ error ] ERROR in function unmount_on_exit [ image-helpers.sh:60 ]
[ error ] debootstrap-ng was interrupted
[ o.k. ] Process terminated

**Comment by 150balbes** [comment]
This error happens if the build environment does not have access to Internet resources (Ubuntu\Debian network repositories).

**Comment by DiApostola** [comment]
There was definitely a DNS issue involved sometime between my last vanilla Armbian build and testing - am re-testing now- thanks!

**Comment by DiApostola** [comment]
Worked just fine - sorry for the trouble!
