### ISSUE TITLE
Build non-interactively

### ISSUE THREAD

**Issue by probonopd** [150balbes/build#55]
How can we build e.g., for a MXQ `m201C_512M` box without being asked any questions?

I am trying to build on a build server and it is not possible to enter anything there during compilation via the keyboard.

**Comment by probonopd** [comment]
Getting

```
Press <Ctrl-C> to abort compilation, <Enter> to ignore and continue

cannot open tty-output
[ error ] ERROR in function source [ main.sh:101 ]
[ error ] No option selected 
[ o.k. ] Process terminated 
ERROR: Job failed: exit code 1
```

**Comment by 150balbes** [comment]
This git is no longer supported.
